version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install --upgrade pip
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - export AWS_REGION=$AWS_REGION
      - REPOSITORY_URI=$ECR_URI
      - $(aws ecr get-login --no-include-email --region $AWS_REGION)
      - export IMAGE_TAG=$(date +%Y%m%d%H%M%S)  # Generate a unique timestamp tag

  build:
    commands:
      - echo "Changing directory to project folder..."
      - pwd
      - cd todonodeapp  # Change to the project folder
      - echo "Building Docker image from todonodeapp directory..."
      - docker build -t $IMAGE_NAME:$IMAGE_TAG .  # Build the image using the current directory

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker tag $IMAGE_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG  # Tag the image for ECR
      - docker push $REPOSITORY_URI:$IMAGE_TAG  # Push the tagged image to ECR
